---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-s3
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  BUCKET_HOST: s3.openshift-storage.svc
  BUCKET_NAME: acm-obs
  BUCKET_PORT: "443"
  BUCKET_REGION: ""
  BUCKET_SUBREGION: ""
